spring:
  datasource:
    driverClassName: org.h2.Driver
    password: sa
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
