CREATE TABLE EMPLOYEE (
	EMPLOYEE_ID INTEGER DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	AGE INTEGER,
	GENDER VARCHAR(6),
	SALARY INTEGER,
	COMPANY_ID INTEGER,
	CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_ID)
);